### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by skalee** [metanorma/reverse_adoc#58]
A test is failing on my computer and in CI since cc75339811e20bcbe7f94196395470cde58fc2ed by @opoudjis. Example of failed build: https://github.com/metanorma/reverse_adoc/actions/runs/697855785. Seems like migration to Marcel gem wasn't that straightforward.

**Comment by skalee** [comment]
Investigation revealed that a mathematical formula is turned into a picture, which is probably incorrect:

> ![001](https://user-images.githubusercontent.com/154287/113379842-ead43100-937a-11eb-9487-c08c5fc2fdfc.gif)

**Comment by ronaldtse** [comment]
Must be indeed 😜

**Comment by opoudjis** [comment]
I was going to change the test, and didn't get to it. Microsoft Word does turn mathematical formulas into pictures, for Legacy support reasons, but it turns out that we are getting this behaviour now happening with some platforms under github actions but not others. Given that mime-types have raised this issue, it is possible that the Legacy image is being generated by word have something wrong with their mind and coding. This is not an issue for this Jam, because we end up ignoring those image renderings of formula anyway, so I will loosen the test condition
