### ISSUE TITLE
Remove unwanted text inserted at the end of Introduction section

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/reverse_adoc#79]
A text of this is structure:
`<title-intro-en> -- <title-main-en> -- <title-part-en>`
is being inserted at the end of *Introduction* section.

It happened when converting the Word document given in https://github.com/metanorma/iso-19144-2/issues/1.
In that case, this part appeared:
`Geographic information --  Classification systems --  Part&nbsp;2: Land Cover Meta Language (LCML)`

**Comment by opoudjis** [comment]
Ah. Thank you for checking this, @HassanAkbar. 

So, that text is indeed in the Word document, but it gets automatically inserted by Metanorma. So @manuelfuenmayor is asking us not to preserve it when we convert the Word document, because Metanorma is going to insert that text regardless.

Which is legitimate as a concern...

... but we cannot anticipate in the general case that this is an ISO document, which repeats the title there. Some SDOs, including ISO, include a repeated title at the start of the main body of text. Documents from other SDOs *do not* insert the title redundantly there, and in the general case, the initial paragraph after the introduction should not be removed.

I'm worried that we cannot tell reliably when the first paragraph at the start of the main section of text is a redundant title, and when it is legitimately part of the text. Given that this tool is meant to be generic (and usable by others), I'm afraid, Manuel, that I don't think we should be stripping that text.
